---

name: build and deploy
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Dockerfiles: [Dockerfile.alpine]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Buildx
        run: |
          for file in ${{ matrix.Dockerfiles }}; do \
            tag=$(echo $file | sed -ie 's|Dockerfile.||g') \
             && docker buildx build \
            --platform linux/arm/v7 \
            --output "type=image,push=false" \
            --tag $tag \
            --file $file . ;\
          done
          

